playbook file
- name: Deploy Database
  hosts: oracle_servers
  become: yes
  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"
        name: config_vars

    - name: Include ansible-role-database-deploy
      include_role:
        name: ansible-role-database-deploy
        tasks_from: main.yml
      vars:
        oracle_host: "{{ config_vars.oracle_host }}"
        github_token: "{{ config_vars.github_token }}"
        username: "{{ config_vars.username }}"
        password: "{{ config_vars.password }}"
        ORACLE_SID: "{{ config_vars.ORACLE_SID }}"
        zip_file_name: "{{ config_vars.zip_file_name }}"
        zip_file_name_1: "{{ config_vars.zip_file_name_1 }}"
        ORACLE_HOME: "{{ config_vars.ORACLE_HOME }}"
        PATH: "{{ config_vars.PATH }}"
        oracle_deployment_dir: "{{ config_vars.oracle_deployment_dir }}"
---------------------------------
config file
oracle_host: "10.15.25.168:5300"
github_token: "{{ lookup('env', 'TOKEN_GITHUB') }}"
username: "{{ lookup('env', 'ORA_USERNAME') }}"
password: "{{ lookup('env', 'ORA_PASSWORD') }}"
ORACLE_SID: "CNVDGUAT"
zip_file_name: "/ansible/UAT_ARTIFACTS/UAT4/{{ lookup('env', 'COMPILE_DATE') }}/RAK_IB_CONVERGENCE_PATCHES_CR_UAT4/DB_SQL"
zip_file_name_1: "{{ zip_file_url_1 | basename }}"
ORACLE_HOME: "/oracle19c/app/oracle/product/19.3.0/db_home"
PATH: "{{ ORACLE_HOME }}/bin:{{ PATH }}"
oracle_deployment_dir: "/backup"
----------------------------------
