name: Deploy Database
on:
  workflow_dispatch:
    inputs:
      compile_date:
        description: 'Compile date to deploy'
        required: true
        type: string
jobs:
  deploy:
    runs-on: 
      group: rakbank-self-hosted-runner
      labels: dehitdevtra1
    steps:
      - name: Checkout mcf_db repository
        uses: actions/checkout@v4
        with:
          repository: rakbank-internal/mcf_db
          ref: ${{ github.event.inputs.branch }}
          #path: ansible-roles
          #token: ${{ secrets.TOKEN_GITHUB }}

      - name: Checkout second repository
        uses: actions/checkout@v4
        with:
          repository: rakbank-internal/enterprise-ansible-roles
          token: ${{ secrets.TOKEN_GITHUB }}
          path: ansible-roles
          ref: Feature

      #- name: Clone enterprise-ansible-roles repository
       # run: |
        #  if [ ! -d "../enterprise-ansible-roles" ]; then
         #  git clone https://github.com/rakbank-internal/enterprise-ansible-roles ../enterprise-ansible-roles
          #else
           #echo "Directory ../enterprise-ansible-roles already exists."
          #fi

      #- name: Debug Working Directory
       # run: |
        #  ls -al
         # pwd
      - name: Run Ansible Playbook
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          ORA_USERNAME: ${{ secrets.ORA_USERNAME }}
          ORA_PASSWORD: ${{ secrets.ORA_PASSWORD }}
          COMPILE_DATE: ${{ github.event.inputs.compile_date }}
        run: |
          cd ${{ github.workspace }}
          ansible-playbook -vvv -b -i inventory.ini ./playbook/mcfdbdeployment.yml --extra-vars "target=oracle_servers destination=${{ github.workspace }} deploy_mode=true rollback_mode=false cacherefresh_mode=false"
----------------------------------

- name: Deploy Database
  hosts: oracle_servers
  become: yes
  become_user: itdevtra

  tasks:
    - name: Include database-deployment-role
      include_role:
        name: database-deployment-role
        tasks_from: main.yml
      vars:
        oracle_host: "10.15.25.168:5300"
        github_token: "{{ lookup('env', 'TOKEN_GITHUB') }}"
        owner: "rakbank-internal"
        repo: "mcf_db"
        branch: "RELEASE-DB-ROLE"
        username: "{{ lookup('env', 'ORA_USERNAME') }}"
        password: "{{ lookup('env', 'ORA_PASSWORD') }}"
        ORACLE_SID: "CNVDGUAT"
        zip_file_name: "/ansible/UAT_ARTIFACTS/UAT4/{{ lookup('env', 'COMPILE_DATE') }}/RAK_IB_CONVERGENCE_PATCHES_CR_UAT4/DB_SQL"
        ORACLE_HOME: "/oracle19c/app/oracle/product/19.3.0/db_home"
        PATH: "{{ ORACLE_HOME }}/bin:{{ PATH }}"
        oracle_deployment_dir: "/backup"

----------------------------------
ansible config


[defaults]
host_key_checking=False
deprecation_warnings=False
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
#roles_path = roles/
roles_path = ansible-roles/roles/
comment_warnings=False
command_warnings=False
inventory = inventory.ini
remote_user = ubuntu
interpreter_python=auto
ANSIBLE_DEPRECATION_WARNINGS=False
ANSIBLE_COMMAND_WARNINGS=False
allow_world_readable_tmpfiles=yes
timeout=30
ansible_pipelining=True
