- name: Deploy War Files to JBoss
  hosts: oracle_servers
  become: itdevtra
  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"
        name: config_vars

    - name: Include ansible-role-oracle-deploy 
      include_role:
        name: ansible-role-oracle-deploy
        tasks_from: main.yml
      vars:
        zip_file_name: "{{ config_vars.zip_file_name }}"  # Pass zip_file_name variable here
        oracle_deployment_dir: "{{ config_vars.oracle_deployment_dir }}"  # Add this line if needed in the role
        username: "{{ config_vars.username }}"  # Add other required variables as needed
        password: "{{ config_vars.password }}"
        oracle_host: "{{ config_vars.oracle_host }}"
        ORACLE_SID: "{{ config_vars.ORACLE_SID }}"
        ORACLE_HOME: "{{ config_vars.ORACLE_HOME }}"
        PATH: "{{ config_vars.PATH }}"
        github_token: "{{ config_vars.github_token }}"
-----------------

TASK [Read configuration from config.yml] **************************************
task path: /ansible/GITHUB_RUNNER/actions-runner10/_work/mcf_db/mcf_db/playbook/mcfdbdeployment.yml:5
ok: [10.15.25.168] => {
    "ansible_facts": {
        "config_vars": {
            "ORACLE_HOME": "/oracle19c/app/oracle/product/19.3.0/db_home",
            "ORACLE_SID": "CNVDGUAT",
            "PATH": "{{ ORACLE_HOME }}/bin:{{ PATH }}",
            "github_token": "{{ lookup('env', 'TOKEN_GITHUB') }}",
            "oracle_deployment_dir": "/backup",
            "oracle_host": "10.15.25.168:5300",
            "password": "{{ lookup('env', 'ORA_PASSWORD') }}",
            "username": "{{ lookup('env', 'ORA_USERNAME') }}",
            "zip_file_name": "/ansible/UAT_ARTIFACTS/UAT4/{{ lookup('env', 'COMPILE_DATE') }}/RAK_IB_CONVERGENCE_PATCHES_CR_UAT4/DB_SQL",
            "zip_file_name_1": "{{ zip_file_url_1 | basename }}"
        }
    },
    "ansible_included_var_files": [
        "/ansible/GITHUB_RUNNER/actions-runner10/_work/mcf_db/mcf_db/config.yml"
    ],
    "changed": false
}
TASK [Include ansible-role-oracle-deploy] **************************************
task path: /ansible/GITHUB_RUNNER/actions-runner10/_work/mcf_db/mcf_db/playbook/mcfdbdeployment.yml:10
TASK [ansible-role-oracle-deploy : Copy SQL files to Target Server] ************
task path: /ansible/GITHUB_RUNNER/actions-runner10/_work/mcf_db/mcf_db/roles/ansible-role-oracle-deploy/tasks/main.yml:2
fatal: [10.15.25.168]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'zip_file_name' is undefined\n\nThe error appears to be in '/ansible/GITHUB_RUNNER/actions-runner10/_work/mcf_db/mcf_db/roles/ansible-role-oracle-deploy/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy SQL files to Target Server\n  ^ here\n"
}
PLAY RECAP *********************************************************************
10.15.25.168               : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
Error: Process completed with exit code 2.
---------------------------------------------

this is my workflow
name: Deploy Database

on:
  workflow_dispatch:
   inputs:
      compile_date:
        description: 'Compile date to deploy'
        required: true 
        type: string

jobs:
  deploy:
    runs-on: 
      group: rakbank-self-hosted-runner
      labels: dehitdevtra1
  

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          ORA_USERNAME: ${{ secrets.ORA_USERNAME }}
          ORA_PASSWORD: ${{ secrets.ORA_PASSWORD }}
          COMPILE_DATE: ${{ github.event.inputs.compile_date }}
        run: |
          cd ${{ github.workspace }}
          ansible-playbook -vvv -b -i inventory.ini ./playbook/mcfdbdeployment.yml --extra-vars "target=oracle_servers GITHUB_WORKSPACE=${{ github.workspace }}"
-------------------------------
this is my playbook file

- name: Deploy War Files to JBoss
  hosts: oracle_servers
  become: itdevtra
  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"
        name: config_vars

    - name: Include ansible-role-oracle-deploy 
      include_role:
        name: ansible-role-oracle-deploy
        tasks_from: main.yml
      vars:
        owner: "{{ config_vars.owner }}"
        repo: "{{ config_vars.repo }}"
        branch: "{{ config_vars.branch }}"
        github_token: "{{ config_vars.github_token }}"	  
-----------------
this is my role/tasks file


- name: Copy SQL files to Target Server
  copy:
    src: "{{ zip_file_name }}/DEPLOY.sql"
    dest: "{{ oracle_deployment_dir }}/DEPLOY.sql"
    
- name: Deploy Database with custom timeout
  become: true
  become_user: itdevtra
  shell: |
    export ORACLE_HOME=/oracle19c/app/oracle/product/19.3.0/db_home
    export PATH=$ORACLE_HOME/bin:$PATH
    sqlplus -s {{ username }}/{{ password }}@{{ oracle_host }}/{{ ORACLE_SID }} @{{ oracle_deployment_dir }}/DEPLOY.sql | tee /tmp/deploy_output.log
    grep -q 'ORA-' /tmp/deploy_output.log && exit 1 || exit 0
  async: 60
  poll: 0
  register: deploy_result

- name: Wait for the deploy task to finish
  async_status:
    jid: "{{ deploy_result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 1
-------------------------
this is ansible.cfg file
[defaults]
host_key_checking=False
deprecation_warnings=False
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
remote_tmp=/tmp
roles_path=roles/
comment_warnings=False
command_warnings=False
interpreter_python=auto
ANSIBLE_DEPRECATION_WARNINGS=False
ANSIBLE_COMMAND_WARNINGS=False
---------------
this is my config file

---
oracle_host: "10.15.25.168:5300"
github_token: "{{ lookup('env', 'TOKEN_GITHUB') }}"
username: "{{ lookup('env', 'ORA_USERNAME') }}"
password: "{{ lookup('env', 'ORA_PASSWORD') }}"
ORACLE_SID: "CNVDGUAT"
zip_file_name: "/ansible/UAT_ARTIFACTS/UAT4/{{ lookup('env', 'COMPILE_DATE') }}/RAK_IB_CONVERGENCE_PATCHES_CR_UAT4/DB_SQL"
zip_file_name_1: "{{ zip_file_url_1 | basename }}"
ORACLE_HOME: "/oracle19c/app/oracle/product/19.3.0/db_home"
PATH: "{{ ORACLE_HOME }}/bin:{{ PATH }}"
oracle_deployment_dir: "/backup"
...
-----------
this is my inventory file

[all:vars]
ansible_user=itdevtra
ansible_ssh_port=22

[oracle_servers]
10.15.25.168

    
